-------------------------------------------------------------------------------
Test set: org.example.pruebaUnitariaTest
-------------------------------------------------------------------------------
Tests run: 11, Failures: 11, Errors: 0, Skipped: 0, Time elapsed: 0.074 sec <<< FAILURE!
org.example.pruebaUnitariaTest.testSumar()  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.NullPointerException: Cannot invoke "org.example.PruebaUnitaria.sumar(int, int)" because "this.pruebaUnitaria" is null
	at org.example.pruebaUnitariaTest.testSumar(pruebaUnitariaTest.java:37)

org.example.pruebaUnitariaTest.testEsPrimo()  Time elapsed: 0.002 sec  <<< FAILURE!
java.lang.NullPointerException: Cannot invoke "org.example.PruebaUnitaria.esPrimo(int)" because "this.pruebaUnitaria" is null
	at org.example.pruebaUnitariaTest.testEsPrimo(pruebaUnitariaTest.java:154)

org.example.pruebaUnitariaTest.testContarLetrasA()  Time elapsed: 0 sec  <<< FAILURE!
java.lang.NullPointerException: Cannot invoke "org.example.PruebaUnitaria.contarLetrasA(String)" because "this.pruebaUnitaria" is null
	at org.example.pruebaUnitariaTest.testContarLetrasA(pruebaUnitariaTest.java:89)

org.example.pruebaUnitariaTest.testCheckPositivos()  Time elapsed: 0 sec  <<< FAILURE!
java.lang.NullPointerException: Cannot invoke "org.example.PruebaUnitaria.checkPositivo(int)" because "this.pruebaUnitaria" is null
	at org.example.pruebaUnitariaTest.testCheckPositivos(pruebaUnitariaTest.java:55)

org.example.pruebaUnitariaTest.testCheckNegativo()  Time elapsed: 0.051 sec  <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception type thrown, expected: <java.lang.IllegalArgumentException> but was: <java.lang.NullPointerException>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:67)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:35)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3128)
	at org.example.pruebaUnitariaTest.testCheckNegativo(pruebaUnitariaTest.java:72)
Caused by: java.lang.NullPointerException: Cannot invoke "org.example.PruebaUnitaria.checkPositivo(int)" because "this.pruebaUnitaria" is null
	at org.example.pruebaUnitariaTest.lambda$testCheckNegativo$0(pruebaUnitariaTest.java:73)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:53)
	... 21 more

org.example.pruebaUnitariaTest.testesMenorAUno()  Time elapsed: 0.007 sec  <<< FAILURE!
java.lang.NullPointerException: Cannot invoke "org.example.PruebaUnitaria.esPrimo(int)" because "this.pruebaUnitaria" is null
	at org.example.pruebaUnitariaTest.testesMenorAUno(pruebaUnitariaTest.java:166)

org.example.pruebaUnitariaTest.testNoEsPrimo()  Time elapsed: 0 sec  <<< FAILURE!
java.lang.NullPointerException: Cannot invoke "org.example.PruebaUnitaria.esPrimo(int)" because "this.pruebaUnitaria" is null
	at org.example.pruebaUnitariaTest.testNoEsPrimo(pruebaUnitariaTest.java:179)

org.example.pruebaUnitariaTest.testFactorial()  Time elapsed: 0.002 sec  <<< FAILURE!
java.lang.NullPointerException: Cannot invoke "org.example.PruebaUnitaria.factorial(int)" because "this.pruebaUnitaria" is null
	at org.example.pruebaUnitariaTest.testFactorial(pruebaUnitariaTest.java:130)

org.example.pruebaUnitariaTest.testRevertirCadena()  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.NullPointerException: Cannot invoke "org.example.PruebaUnitaria.revertirCadena(String)" because "this.pruebaUnitaria" is null
	at org.example.pruebaUnitariaTest.testRevertirCadena(pruebaUnitariaTest.java:117)

org.example.pruebaUnitariaTest.testContieneElemento()  Time elapsed: 0.003 sec  <<< FAILURE!
java.lang.NullPointerException: Cannot invoke "org.example.PruebaUnitaria.contieneElemento(java.util.List, String)" because "this.pruebaUnitaria" is null
	at org.example.pruebaUnitariaTest.testContieneElemento(pruebaUnitariaTest.java:104)

org.example.pruebaUnitariaTest.testFactorialMenosACero()  Time elapsed: 0 sec  <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception type thrown, expected: <java.lang.IllegalArgumentException> but was: <java.lang.NullPointerException>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:67)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:35)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3128)
	at org.example.pruebaUnitariaTest.testFactorialMenosACero(pruebaUnitariaTest.java:143)
Caused by: java.lang.NullPointerException: Cannot invoke "org.example.PruebaUnitaria.factorial(int)" because "this.pruebaUnitaria" is null
	at org.example.pruebaUnitariaTest.lambda$testFactorialMenosACero$1(pruebaUnitariaTest.java:144)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:53)
	... 21 more

